spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todoProjectDB
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update





